### ISSUE TITLE
SSL Cert Error

### ISSUE THREAD

**Issue by watbulb** [firepick/firepick.github.io#4]
Hey, so when clicking on the firepick.org links on the README.md I'm getting SSL cert errors on Firefox.

**Comment by jandetlefsen** [comment]
that's cause github pages does not support https afaik.

**Comment by firepick1** [comment]
Thanks, Jan.

On Wednesday, May 11, 2016, Jan Detlefsen notifications@github.com wrote:

> that's cause it's not actually https, just need to change link. in the
> readme.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/firepick/firepick.github.io/issues/4#issuecomment-218664008

## 

Karl Lew
FIREPICK SERVICES LLC
karl@firepick.org
www.firepick.org
